### ISSUE TITLE
neural_nets/utils/utils.py line 797 has a bug!

### ISSUE THREAD

**Issue by Z-zhe** [ddbourgin/numpy-ml#32] opened 2019-07-20 06:14 UTC
hi, I think neural_nets/utils/utils.py line 797 has a bug!

### your code
i0, i1 = i * s, (i * s) + fr * (d + 1) - d
j0, j1 = j * s, (j * s) + fc * (d + 1) - d

### right code
i0, i1 = i * s, (i * s) + fr
j0, j1 = j * s, (j * s) + fc

> because fr and fc are already dilated size !

**Comment by ddbourgin** [comment] 2019-07-25 19:50
Thanks for this @Z-zhe! Sorry I haven't had a chance to take a look at this -- I will shortly :)

**Comment by ddbourgin** [comment] 2019-07-28 20:06
Hi @Z-zhe - just checking in to see why this was closed. Did you decide it's not a bug after all? Happy to take a look if you still think there's an error!

**Comment by Z-zhe** [comment] 2019-07-29 00:39
Sorry, this is a misoperation. Please check your code to fix this bug, thanks!

**Comment by ddbourgin** [comment] 2019-07-29 22:09
Hi @Z-zhe - finally had a look at this, and you're right! Will update the code momentarily :)

**Comment by ddbourgin** [comment] 2019-07-30 05:06
Fixed - see https://github.com/ddbourgin/numpy-ml/commit/3bef55558d0142a2903d5f98b27a7572e17ddbcc. Thanks @Z-zhe! Closing.

**Closed by ddbourgin** 2019-07-30 05:06 UTC
Labels: bug
